INSERT INTO amino_acids (amino_acid_name, one_letter_code, three_letter_code, molecular_weight, amino_acid_type, id) VALUES
('Alanine', 'A', 'Ala', 89, 'NONPOLAR',1),
('Arginine', 'R', 'Arg', 174, 'BASIC',2),
('Asparagine', 'N', 'Asn', 132, 'POLAR_UNCHARGED',3),
('Aspartic acid', 'D', 'Asp', 133, 'ACIDIC',4),
('Cysteine', 'C', 'Cys', 121, 'NONPOLAR',5),
('Glutamic acid', 'E', 'Glu', 147, 'ACIDIC',6),
('Glutamine', 'Q', 'Gln', 146, 'POLAR_UNCHARGED',7),
('Glycine', 'G', 'Gly', 75, 'NONPOLAR',8),
('Histidine', 'H', 'His', 155, 'BASIC',9),
('Isoleucine', 'I', 'Ile', 131, 'NONPOLAR',10),
('Leucine', 'L', 'Leu', 131, 'NONPOLAR',11),
('Lysine', 'K', 'Lys', 146, 'BASIC',12),
('Methionine', 'M', 'Met', 149, 'NONPOLAR',13),
('Phenylalanine', 'F', 'Phe', 165, 'AROMATIC',14),
('Proline', 'P', 'Pro', 115, 'NONPOLAR',15),
('Serine', 'S', 'Ser', 105, 'POLAR_UNCHARGED',16),
('Threonine', 'T', 'Thr', 119, 'POLAR_UNCHARGED',17),
('Tryptophan', 'W', 'Trp', 204, 'AROMATIC',18),
('Tyrosine', 'Y', 'Tyr', 181, 'AROMATIC',19),
('Valine', 'V', 'Val', 117, 'NONPOLAR',20);
